#!/bin/bash
URL="http://192.168.1.1/cgi-bin/luci/rpc/sys?auth=$1"
DATA='
{
    "jsonrpc": "2.0",
    "method": "exec",
    "params": ["/usr/bin/luci-bwc -c"],
    "id": 1
}'
curl -i -X POST -d "$DATA" $URL
